### ISSUE TITLE
Hardfaults after blinking on then off

### ISSUE THREAD

**Issue by nametable** [PicoCPP/RPI-pico-FreeRTOS#1]
I am unsure what the issue is however I notice that when I run the program the led goes on, then off. After that, it doesn't do anything. From what I see from looking at the debugger, it seems there is a hard fault...

```
target halted due to debug-request, current mode: Thread
xPSR: 0x01000000 pc: 0x00000178 msp: 0x20041f00

Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x100002d2 in unhandled_user_irq_num_in_r0 ()
(gdb)
```

I am using one pico as a debugger for the other. Maybe this bug is due to an unhandled interrupt? Maybe I am doing something wrong...

Thanks,
Logan

**Comment by PicoCPP** [comment]
What version of arm GCC did you compile this with? I compiled with q4 2019 on debug.

It could be that you need to increase the stack size of the main thread. Try 1024 words instead of 512.  Sometimes different GCC versions have varying stack requirements.

Does the call stack say what irq isn't implemented? And can you make sure both interrupts get hit in the interrupts.c file?

**Comment by nametable** [comment]
> What version of arm GCC did you compile this with? I compiled with q4 2019 on debug.

arm-none-eabi-gcc (Arch Repository) 10.2.0

> It could be that you need to increase the stack size of the main thread. Try 1024 words instead of 512. Sometimes different GCC versions have varying stack requirements.

Tried changing to 1024 words and that didn't help.
>Does the call stack say what irq isn't implemented? And can you make sure both interrupts get hit in the interrupts.c file?

`isr_pendsv` and `isr_systick` are happening, I added some `asm("bkpt")`s inside them. Side note, your `interrrupts.c` has 3 `r`s.

Here is the backtrace after the fault:
```
(gdb) bt
#0  0x100002c4 in isr_hardfault ()
#1  <signal handler called>
#2  0x10001d00 in prvCheckTasksWaitingTermination () at /home/logan/Documents/RaspberryPi/Pico/RPI-pico-FreeRTOS/FreeRTOS-Kernel/tasks.c:3694
#3  prvIdleTask (pvParameters=<optimized out>) at /home/logan/Documents/RaspberryPi/Pico/RPI-pico-FreeRTOS/FreeRTOS-Kernel/tasks.c:3440
#4  0x10003320 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Here is where the first break happens due to fault:
![image](https://user-images.githubusercontent.com/19422826/106630817-294f9a00-654a-11eb-8945-ba5d1b757d05.png)

**Comment by PicoCPP** [comment]
Thanks for the information, I'll upgrade my toolchain to the same as yours.

Seems like isr_irq9 is firing. How strange, I would expect that interrupt to be disabled since it's a user one.

You could try stubbing isr_irq9 and make it do nothing. I think it's typical a hard fault would happen without it implemented

**Comment by PicoCPP** [comment]
I had a look and can create a hard fault when in release build type, looking into it now.

**Comment by PicoCPP** [comment]
I have pushed a patch that may help to bugfix/HardFaultsUnderRelease. Which has disabled static allocation  which I found to cause a hard fault.
I am looking into why though.

**Comment by PicoCPP** [comment]
See https://github.com/PicoCPP/RPI-pico-FreeRTOS/issues/2#issuecomment-771944987 for an explanation, I have pushed two commits to that branch. Fingers crossed it resolves the issue for you, debugging Cortex m0 hardfaults are  a nightmare
